version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bitlabInternProjectDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Daniyal777.
      - SPRING_LIQUIBASE_ENABLED=true
      - SPRING_LIQUIBASE_CHANGELOG=classpath:db/changelog/changes/changelog-master.xml
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=bitlabInternProjectDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Daniyal777.
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
